version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: my_postgres_db
    environment:
      POSTGRES_DB: countries_info
      POSTGRES_USER: tsg
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: